/**
 * Proves the TypeScript build gate is real.
 *
 * Type errors used to be waved through by `typescript.ignoreBuildErrors` in
 * next.config.mjs, so a broken API contract could ship. This script is the
 * regression test for that: it fails CI if the escape hatch comes back, and it
 * proves the gate still bites by deliberately introducing a type error and
 * asserting that `tsc` rejects it.
 */
import { execFileSync } from "child_process"
import { existsSync, readFileSync, rmSync, writeFileSync } from "fs"
import { createRequire } from "module"
import { dirname, resolve } from "path"

const require = createRequire(import.meta.url)
const typescriptCli = resolve(dirname(require.resolve("typescript/package.json")), "bin/tsc")

/** Config keys that would silently disable a build gate if reintroduced. */
const FORBIDDEN_CONFIG = [
  { pattern: /ignoreBuildErrors\s*:\s*true/, name: "typescript.ignoreBuildErrors" },
  { pattern: /ignoreDuringBuilds\s*:\s*true/, name: "eslint.ignoreDuringBuilds" },
]

/**
 * Written, compiled, and deleted by this script. It lives under `lib/` so it is
 * covered by the project's TypeScript include globs — a probe outside the
 * compiler's view would pass no matter how broken the gate is.
 */
const PROBE_PATH = "lib/__typecheck-gate-probe__.ts"
const PROBE_SOURCE = `// Generated by scripts/check-typecheck-gate.ts. Deleted again before the script exits.
export const deliberateTypeError: string = 42
`

function checkNextConfig(): void {
  const config = readFileSync("next.config.mjs", "utf8")

  for (const { pattern, name } of FORBIDDEN_CONFIG) {
    if (pattern.test(config)) {
      throw new Error(
        `next.config.mjs enables ${name}. Production builds must fail on type errors; ` +
          "fix the offending types instead of suppressing the gate.",
      )
    }
  }

  console.log("next.config.mjs declares no build-error suppression.")
}

/**
 * A file-level nocheck directive exempts a whole file from the gate — the same
 * failure mode as `ignoreBuildErrors`, with a narrower blast radius. Only a
 * line-scoped `@ts-expect-error`, which itself errors once the underlying
 * problem is fixed, is an acceptable suppression.
 *
 * The directive is assembled rather than written out so this script does not
 * match itself and does not need to be exempted from its own check.
 */
const NOCHECK_DIRECTIVE = ["@ts", "nocheck"].join("-")

function checkNoFileLevelSuppressions(): void {
  const tracked = execFileSync("git", ["ls-files", "*.ts", "*.tsx"], { encoding: "utf8" })
    .split(/\r?\n/)
    .map((file) => file.trim())
    .filter(Boolean)

  const suppressed = tracked.filter((file) => readFileSync(file, "utf8").includes(NOCHECK_DIRECTIVE))

  if (suppressed.length > 0) {
    throw new Error(
      `${NOCHECK_DIRECTIVE} exempts whole files from the gate. Remove it from: ${suppressed.join(", ")}. ` +
        "Use a line-scoped @ts-expect-error with a comment if a type is genuinely unrepresentable.",
    )
  }

  console.log(`No ${NOCHECK_DIRECTIVE} directive in ${tracked.length} tracked TypeScript files.`)
}

function runTypecheck(): { ok: boolean; output: string } {
  try {
    const output = execFileSync(process.execPath, [typescriptCli, "--noEmit", "--incremental", "false"], {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
    })
    return { ok: true, output }
  } catch (error) {
    const failure = error as { stdout?: string; stderr?: string }
    return { ok: false, output: `${failure.stdout ?? ""}${failure.stderr ?? ""}` }
  }
}

function checkGateRejectsTypeErrors(): void {
  if (existsSync(PROBE_PATH)) {
    throw new Error(`${PROBE_PATH} already exists. Remove it — it is a scratch file, never a committed one.`)
  }

  writeFileSync(PROBE_PATH, PROBE_SOURCE)

  try {
    const { ok, output } = runTypecheck()

    if (ok) {
      throw new Error(
        "The typecheck gate accepted a deliberate type error. Compiler strictness or the " +
          "tsconfig include list has been weakened.",
      )
    }

    if (!output.includes("__typecheck-gate-probe__")) {
      throw new Error(`The typecheck failed, but not on the probe file. Output:\n${output}`)
    }

    console.log("Typecheck rejects an introduced type error, as expected.")
  } finally {
    rmSync(PROBE_PATH, { force: true })
  }
}

checkNextConfig()
checkNoFileLevelSuppressions()
checkGateRejectsTypeErrors()
console.log("TypeScript build gate verified.")
