import type { AuthorizationAction } from "./policy"

export type RoutePolicy = { access: "public"; rationale: string } | { access: "authenticated" | "sensitive"; action: AuthorizationAction; rationale: string }
const publicRoute = (rationale: string): RoutePolicy => ({ access: "public", rationale })
const policy = (action: AuthorizationAction, rationale: string, access: "authenticated" | "sensitive" = "sensitive"): RoutePolicy => ({ access, action, rationale })

export const ROUTE_POLICY_INVENTORY: Record<string, RoutePolicy> = {
  "GET /api/account/profile": policy("account:read", "Principal profile only", "authenticated"),
  "PATCH /api/account/profile": policy("account:update", "Principal profile only"),
  "GET /api/activity": policy("activity:read", "Principal activity only", "authenticated"),
  "PATCH /api/activity": policy("activity:update", "Principal activity only"),
  "GET /api/admin/approvals": policy("admin:report", "Maker-checker approval queue"),
  "GET /api/admin/approvals/[id]": policy("admin:report", "Maker-checker approval detail"),
  "POST /api/admin/approvals/[id]/approve": policy("admin:settings:manage", "Maker-checker approval decision"),
  "POST /api/admin/approvals/[id]/reject": policy("admin:settings:manage", "Maker-checker approval decision"),
  "POST /api/admin/approvals/[id]/cancel": policy("admin:settings:manage", "Maker-checker approval cancellation"),
  "POST /api/admin/data-integrity/findings/[id]/suppress": policy("admin:settings:manage", "Administrative integrity finding suppression"),
  "POST /api/admin/data-integrity/repair": policy("admin:settings:manage", "Administrative integrity repair"),
  "GET /api/admin/data-integrity/scan": policy("admin:report", "Administrative integrity scan results"),
  "POST /api/admin/data-integrity/scan": policy("admin:report", "Administrative integrity scan execution"),
  "GET /api/admin/dashboard-stats": policy("admin:report", "Administrative metrics"),
  "GET /api/admin/issues": policy("admin:issue:manage", "Administrative issue data"),
  "POST /api/admin/issues": policy("admin:issue:manage", "Administrative issue mutation"),
  "GET /api/admin/issues/[id]": policy("admin:issue:manage", "Administrative issue data"),
  "PATCH /api/admin/issues/[id]": policy("admin:issue:manage", "Administrative issue mutation"),
  "GET /api/admin/kyc-documents": policy("kyc:review", "Sensitive KYC records"),
  "POST /api/admin/kyc-documents": policy("kyc:review", "Sensitive KYC document creation"),
  "POST /api/admin/kyc-migrate": policy("kyc:review", "Sensitive KYC migration"),
  "GET /api/admin/kyc-requests": policy("kyc:review", "Sensitive KYC records"),
  "POST /api/admin/migrate-vehicle-status": policy("vehicle:manage", "Privileged migration"),
  "GET /api/admin/platform-settings": policy("admin:settings:manage", "Administrative settings"),
  "PUT /api/admin/platform-settings": policy("admin:settings:manage", "Administrative settings mutation"),
  "GET /api/admin/reconciliation/discrepancies": policy("admin:report", "Reconciliation discrepancies"),
  "POST /api/admin/reconciliation/remediate": policy("admin:settings:manage", "Reconciliation remediation"),
  "GET /api/admin/reconciliation/run": policy("admin:report", "Reconciliation runs"),
  "POST /api/admin/reconciliation/run": policy("admin:report", "Reconciliation run execution"),
  "GET /api/admin/reports/export": policy("admin:report", "PII-bearing report export"),
  "GET /api/admin/settlement/timeline": policy("admin:report", "Administrative settlement timeline & diagnostics"),
  "POST /api/admin/settlement/timeline": policy("admin:settings:manage", "Administrative settlement state remediation"),
  "GET /api/admin/users/export": policy("admin:report", "PII-bearing user export"),
  "POST /api/auth/admin/signup": publicRoute("Bootstrap endpoint has its own one-time secret controls"),
  "GET /api/auth/admin/status": publicRoute("Returns only bootstrap availability"),
  "POST /api/auth/login": publicRoute("Authentication entry point"),
  "POST /api/auth/logout": publicRoute("Session-clearing endpoint"),
  "GET /api/auth/me": policy("account:read", "Current principal", "authenticated"),
  "POST /api/auth/privy/sync": publicRoute("Privy token verification establishes principal"),
  "POST /api/auth/signup": publicRoute("Disabled legacy endpoint"),
  "POST /api/auth/stellar/link": policy("wallet:adjust", "Links wallet identity"),
  "GET /api/driver/virtual-account": policy("wallet:read", "Driver-owned wallet"),
  "POST /api/driver/payments/initialize": policy("repayment:record", "Driver-owned active contract"),
  "GET /api/fleet/documents": policy("vehicle:read", "Fleet documents"),
  "POST /api/fleet/documents": policy("vehicle:manage", "Fleet document management"),
  "GET /api/fleet/downtime": policy("vehicle:read", "Fleet downtime records"),
  "POST /api/fleet/downtime": policy("vehicle:manage", "Fleet downtime management"),
  "GET /api/fleet/inspections": policy("vehicle:read", "Fleet inspection records"),
  "POST /api/fleet/inspections": policy("vehicle:manage", "Fleet inspection management"),
  "GET /api/fleet/maintenance": policy("vehicle:read", "Fleet maintenance records"),
  "POST /api/fleet/maintenance": policy("vehicle:manage", "Fleet maintenance creation"),
  "PATCH /api/fleet/maintenance": policy("vehicle:manage", "Fleet maintenance mutation"),
  "POST /api/invest": publicRoute("Disabled legacy endpoint"),
  "GET /api/investments": policy("investment:read", "Investor ownership or admin"),
  "GET /api/investor/virtual-account": policy("wallet:read", "Investor-owned wallet"),
  "GET /api/kyc-documents": policy("kyc:document:read", "Owner or reviewer only"),
  "POST /api/kyc-documents/sign": policy("kyc:document:read", "KYC document signing"),
  "GET /api/loans": policy("loan:read", "Driver ownership or admin"),
  "POST /api/loans": policy("loan:create", "KYC-approved driver principal"),
  "PUT /api/loans": policy("loan:approve", "Admin with valid workflow transition"),
  "GET /api/notifications": policy("notification:read", "Owner or admin"),
  "POST /api/notifications": policy("notification:create", "Administrative operation"),
  "POST /api/payments/down-payment": policy("repayment:record", "Owner-derived loan"),
  "POST /api/payments/initialize": policy("wallet:adjust", "Principal wallet operation"),
  "POST /api/payments/verify": policy("wallet:adjust", "Principal wallet verification"),
  "POST /api/payments/webhook": publicRoute("Provider signature verified webhook"),
  "GET /api/pools": policy("pool:read", "Authenticated catalogue", "authenticated"),
  "POST /api/pools": policy("pool:manage", "Admin or eligible investor"),
  "GET /api/pools/[poolId]": policy("pool:read", "Authenticated pool", "authenticated"),
  "POST /api/pools/[poolId]/invest": policy("investment:create", "KYC-approved investor principal"),
  "POST /api/send-email": policy("email:send", "Administrative provider operation"),
  "GET /api/transactions": policy("wallet:read", "Principal ledger or admin"),
  "GET /api/transactions/ledger": policy("wallet:read", "Principal ledger or admin"),
  "GET /api/transactions/ledger/export": policy("wallet:read", "Principal export or admin"),
  "POST /api/upload": policy("file:upload", "Authenticated KYC owner"),
  "GET /api/users": policy("admin:user:manage", "Administrative user directory"),
  "POST /api/users": policy("admin:user:manage", "Administrative user creation"),
  "GET /api/users/[id]": policy("admin:user:manage", "Admin or own account"),
  "PUT /api/users/[id]": policy("admin:user:manage", "Privileged user mutation"),
  "DELETE /api/users/[id]": policy("admin:user:manage", "Privileged user deletion"),
  "POST /api/vehicle": publicRoute("Disabled legacy endpoint"),
  "GET /api/vehicles": policy("vehicle:read", "Authenticated fleet catalogue", "authenticated"),
  "POST /api/vehicles": policy("vehicle:manage", "Administrative vehicle creation"),
  "GET /api/vehicles/[id]": policy("vehicle:read", "Authenticated vehicle", "authenticated"),
  "PUT /api/vehicles/[id]": policy("vehicle:manage", "Administrative vehicle mutation"),
  "DELETE /api/vehicles/[id]": policy("vehicle:manage", "Administrative vehicle deletion"),
  "GET /api/wallet/summary": policy("wallet:read", "Principal wallet only"),
}
